trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pylint --disable=R,C hello.py
  displayName: 'Lint with pylint'

- script: |
    pytest
  displayName: 'Test with pytest'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '<Your Azure Service Connection>'
    appName: '<Your App Service Name>'
    package: $(System.DefaultWorkingDirectory)/**/*.zip